# Generated by Django 4.2.19 on 2025-05-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gstinverification',
            table='GSTIN_Details',
        ),
    ]
