# Generated by Django 4.2.19 on 2025-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_gstinverification_address_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstinverification',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gstinverification',
            name='user_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
